<?php
/**
 * List of actions for the log
 *
 * @package		ProjectSend
 *
 */
global $activities_references;
$activities_references = array(
							0	=> __('ProjecSend has been installed','cftp_admin'),
							1	=> __('Account logs in through the form','cftp_admin'),
							24	=> __('Account logs in through cookies','cftp_admin'),
							31	=> __('Account (user or client) logs out','cftp_admin'),
							2	=> __('A user creates a new user account','cftp_admin'),
							3	=> __('A user creates a new client account','cftp_admin'),
							4	=> __('A client registers an account for himself','cftp_admin'),
							5	=> __('A file is uploaded by an user','cftp_admin'),
							6	=> __('A file is uploaded by a client','cftp_admin'),
							7	=> __('A file is downloaded by a user (on "Client view" mode)','cftp_admin'),
							8	=> __('A file is downloaded by a client','cftp_admin'),
							9	=> __('A zip file was generated by a client','cftp_admin'),
							10	=> __('A file has been unassigned from a client.','cftp_admin'),
							11	=> __('A file has been unassigned from a group','cftp_admin'),
							12	=> __('A file has been deleted','cftp_admin'),
							13	=> __('A user was edited','cftp_admin'),
							14	=> __('A client was edited','cftp_admin'),
							15	=> __('A group was edited','cftp_admin'),
							16	=> __('A user was deleted','cftp_admin'),
							17	=> __('A client was deleted','cftp_admin'),
							18	=> __('A group was deleted','cftp_admin'),
							19	=> __('A client account was activated','cftp_admin'),
							20	=> __('A client account was deactivated','cftp_admin'),
							27	=> __('A user account was activated','cftp_admin'),
							28	=> __('A user account was deactivated','cftp_admin'),
							21	=> __('A file was marked as hidden','cftp_admin'),
							22	=> __('A file was marked as visible','cftp_admin'),
							23	=> __('A user creates a new group','cftp_admin'),
							25	=> __('A file is assigned to a client','cftp_admin'),
							26	=> __('A file is assigned to a group','cftp_admin'),
							27	=> __('A user account was marked as active','cftp_admin'), // @todo check repetition
							28	=> __('A user account was marked as inactive','cftp_admin'),
							29	=> __('The logo on "Branding" was changed','cftp_admin'),
							30	=> __('ProjectSend was updated','cftp_admin'),
							32	=> __('A system user edited a file.','cftp_admin'),
							33	=> __('A client edited a file.','cftp_admin'),
							34	=> __('A client created a category.','cftp_admin'),
							35	=> __('A client edited a category.','cftp_admin'),
							36	=> __('A client deleted a category.','cftp_admin'),
							37	=> __('An anonymous user downloaded a public file.','cftp_admin'),
							38	=> __('A client account request was processed.','cftp_admin'),
							39	=> __("A client's groups membership requests were processed.",'cftp_admin'),
						);
